import { Command } from 'nestjs-command';
import { Injectable } from '@nestjs/common';
import { CitiesRepository } from '../../cities/repositories/cities.repository';

@Injectable()
export class SeedCitiesCommand {
  constructor(private readonly citiesRepository: CitiesRepository) {}

  @Command({ command: 'seed:cities', describe: 'Seed cities (partidos) data' })
  async action(): Promise<void> {
    console.log('🌱 Seeding cities...');

    const partidos = [
      { name: 'Adolfo Alsina', slug: 'adolfo-alsina' },
      { name: 'Adolfo Gonzales Chaves', slug: 'adolfo-gonzales-chaves' },
      { name: 'Alberti', slug: 'alberti' },
      { name: 'Almirante Brown', slug: 'almirante-brown' },
      { name: 'Arrecifes', slug: 'arrecifes' },
      { name: 'Avellaneda', slug: 'avellaneda' },
      { name: 'Ayacucho', slug: 'ayacucho' },
      { name: 'Azul', slug: 'azul' },
      { name: 'Bahía Blanca', slug: 'bahia-blanca' },
      { name: 'Balcarce', slug: 'balcarce' },
      { name: 'Baradero', slug: 'baradero' },
      { name: 'Benito Juárez', slug: 'benito-juarez' },
      { name: 'Berazategui', slug: 'berazategui' },
      { name: 'Berisso', slug: 'berisso' },
      { name: 'Bolívar', slug: 'bolivar' },
      { name: 'Bragado', slug: 'bragado' },
      { name: 'Brandsen', slug: 'brandsen' },
      { name: 'Campana', slug: 'campana' },
      { name: 'Cañuelas', slug: 'canuelas' },
      { name: 'Capitán Sarmiento', slug: 'capitan-sarmiento' },
      { name: 'Carlos Casares', slug: 'carlos-casares' },
      { name: 'Carlos Tejedor', slug: 'carlos-tejedor' },
      { name: 'Carmen de Areco', slug: 'carmen-de-areco' },
      { name: 'Castelli', slug: 'castelli' },
      { name: 'Colón', slug: 'colon' },
      { name: 'Coronel Dorrego', slug: 'coronel-dorrego' },
      { name: 'Coronel Pringles', slug: 'coronel-pringles' },
      { name: 'Coronel Rosales', slug: 'coronel-rosales' },
      { name: 'Coronel Suárez', slug: 'coronel-suarez' },
      { name: 'Chacabuco', slug: 'chacabuco' },
      { name: 'Chascomús', slug: 'chascomus' },
      { name: 'Chivilcoy', slug: 'chivilcoy' },
      { name: 'Daireaux', slug: 'daireaux' },
      { name: 'Dolores', slug: 'dolores' },
      { name: 'Ensenada', slug: 'ensenada' },
      { name: 'Escobar', slug: 'escobar' },
      { name: 'Esteban Echeverría', slug: 'esteban-echeverria' },
      { name: 'Exaltación de la Cruz', slug: 'exaltacion-de-la-cruz' },
      { name: 'Ezeiza', slug: 'ezeiza' },
      { name: 'Florencio Varela', slug: 'florencio-varela' },
      { name: 'Florentino Ameghino', slug: 'florentino-ameghino' },
      { name: 'General Alvarado', slug: 'general-alvarado' },
      { name: 'General Alvear', slug: 'general-alvear' },
      { name: 'General Arenales', slug: 'general-arenales' },
      { name: 'General Belgrano', slug: 'general-belgrano' },
      { name: 'General Guido', slug: 'general-guido' },
      { name: 'General Juan Madariaga', slug: 'general-juan-madariaga' },
      { name: 'General La Madrid', slug: 'general-la-madrid' },
      { name: 'General Las Heras', slug: 'general-las-heras' },
      { name: 'General Lavalle', slug: 'general-lavalle' },
      { name: 'General Paz', slug: 'general-paz' },
      { name: 'General Pinto', slug: 'general-pinto' },
      { name: 'General Pueyrredón', slug: 'general-pueyrredon' },
      { name: 'General Rodríguez', slug: 'general-rodriguez' },
      { name: 'General San Martín', slug: 'general-san-martin' },
      { name: 'General Viamonte', slug: 'general-viamonte' },
      { name: 'General Villegas', slug: 'general-villegas' },
      { name: 'Guaminí', slug: 'guamini' },
      { name: 'Hipólito Yrigoyen', slug: 'hipolito-yrigoyen' },
      { name: 'Hurlingham', slug: 'hurlingham' },
      { name: 'Ituzaingó', slug: 'ituzaingo' },
      { name: 'José C. Paz', slug: 'jose-c-paz' },
      { name: 'Junín', slug: 'junin' },
      { name: 'La Costa', slug: 'la-costa' },
      { name: 'La Matanza', slug: 'la-matanza' },
      { name: 'La Plata', slug: 'la-plata' },
      { name: 'Lanús', slug: 'lanus' },
      { name: 'Laprida', slug: 'laprida' },
      { name: 'Las Flores', slug: 'las-flores' },
      { name: 'Leandro N. Alem', slug: 'leandro-n-alem' },
      { name: 'Lincoln', slug: 'lincoln' },
      { name: 'Lobería', slug: 'loberia' },
      { name: 'Lobos', slug: 'lobos' },
      { name: 'Lomas de Zamora', slug: 'lomas-de-zamora' },
      { name: 'Luján', slug: 'lujan' },
      { name: 'Magdalena', slug: 'magdalena' },
      { name: 'Maipú', slug: 'maipu' },
      { name: 'Malvinas Argentinas', slug: 'malvinas-argentinas' },
      { name: 'Mar Chiquita', slug: 'mar-chiquita' },
      { name: 'Marcos Paz', slug: 'marcos-paz' },
      { name: 'Mercedes', slug: 'mercedes' },
      { name: 'Merlo', slug: 'merlo' },
      { name: 'Monte', slug: 'monte' },
      { name: 'Monte Hermoso', slug: 'monte-hermoso' },
      { name: 'Moreno', slug: 'moreno' },
      { name: 'Morón', slug: 'moron' },
      { name: 'Navarro', slug: 'navarro' },
      { name: 'Necochea', slug: 'necochea' },
      { name: 'Nueve de Julio', slug: 'nueve-de-julio' },
      { name: 'Olavarría', slug: 'olavarria' },
      { name: 'Patagones', slug: 'patagones' },
      { name: 'Pehuajó', slug: 'pehuajo' },
      { name: 'Pellegrini', slug: 'pellegrini' },
      { name: 'Pergamino', slug: 'pergamino' },
      { name: 'Pila', slug: 'pila' },
      { name: 'Pilar', slug: 'pilar' },
      { name: 'Pinamar', slug: 'pinamar' },
      { name: 'Presidente Perón', slug: 'presidente-peron' },
      { name: 'Puán', slug: 'puan' },
      { name: 'Punta Indio', slug: 'punta-indio' },
      { name: 'Quilmes', slug: 'quilmes' },
      { name: 'Ramallo', slug: 'ramallo' },
      { name: 'Rauch', slug: 'rauch' },
      { name: 'Rivadavia', slug: 'rivadavia' },
      { name: 'Rojas', slug: 'rojas' },
      { name: 'Roque Pérez', slug: 'roque-perez' },
      { name: 'Saavedra', slug: 'saavedra' },
      { name: 'Saladillo', slug: 'saladillo' },
      { name: 'Salliqueló', slug: 'salliquelo' },
      { name: 'Salto', slug: 'salto' },
      { name: 'San Andrés de Giles', slug: 'san-andres-de-giles' },
      { name: 'San Antonio de Areco', slug: 'san-antonio-de-areco' },
      { name: 'San Cayetano', slug: 'san-cayetano' },
      { name: 'San Fernando', slug: 'san-fernando' },
      { name: 'San Isidro', slug: 'san-isidro' },
      { name: 'San Miguel', slug: 'san-miguel' },
      { name: 'San Nicolás', slug: 'san-nicolas' },
      { name: 'San Pedro', slug: 'san-pedro' },
      { name: 'San Vicente', slug: 'san-vicente' },
      { name: 'Suipacha', slug: 'suipacha' },
      { name: 'Tandil', slug: 'tandil' },
      { name: 'Tapalqué', slug: 'tapalque' },
      { name: 'Tigre', slug: 'tigre' },
      { name: 'Tordillo', slug: 'tordillo' },
      { name: 'Tornquist', slug: 'tornquist' },
      { name: 'Trenque Lauquen', slug: 'trenque-lauquen' },
      { name: 'Tres Arroyos', slug: 'tres-arroyos' },
      { name: 'Tres de Febrero', slug: 'tres-de-febrero' },
      { name: 'Tres Lomas', slug: 'tres-lomas' },
      { name: 'Veinticinco de Mayo', slug: 'veinticinco-de-mayo' },
      { name: 'Vicente López', slug: 'vicente-lopez' },
      { name: 'Villa Gesell', slug: 'villa-gesell' },
      { name: 'Villarino', slug: 'villarino' },
      { name: 'Zárate', slug: 'zarate' },
    ];

    const existingCities = await this.citiesRepository.find();

    if (existingCities.length > 0) {
      console.log(
        `⚠️  Cities already seeded (${existingCities.length} found). Skipping...`,
      );
      return;
    }

    const cities = this.citiesRepository.create(partidos);
    await this.citiesRepository.save(cities);

    console.log(`✅ Successfully seeded ${cities.length} cities`);
  }
}
